module.exports = {
    stock_count_node: "stock_count",
    expiry_time_node: "expiry_time",
    zero_sales_count_node: "zero_sales_count",
    last_scanned_count_node: "last_scanned_count",
    dispenser_status_node: "dispenser_status",
    load_time_node: "load_time",
    dispenser_queue_node: "dispenser_queue",
    dispense_id_node: "dispense_id",
    bill_no_node: "bill_number",
    expiry_slots_node: "expiry_slots",
    plc_config_node: "plc_config",
    outlet_config_node: "outlet_config",
    start_of_day_flag: "start_of_day",
    test_mode_flag: "test_mode",
    stop_orders_flag: "stop_orders",
    unscanned_slots_node: "unscanned_slots",
    last_load_info_node: "last_load_info",
    last_load_tmp_node: "last_load_info_tmp",
    loading_issue_items_node: "loading_issue_items",
    reconcile_stock_count_node: "reconcile_stock_count",
    barcode_comparision: "barcode_comparision",
    po_details_node: "po_details",
    reconcile_remarks_node: "reconcile_remarks",
    session_time_node: "outlet_session_timings",
    outlet_session_node: 'outlet_session',
    // done by the peerbits
    outlet_menu_items: "outlet_menu_items",
    staff_roaster_node: "staff_roaster",
    bill_print_info_node: "bill_print_info",
    direct_bill_info_node: "direct_bill_info",
    start_of_day_signal: "start_of_day_signal",
    supplies_detail_node: "supplies_detail",
    supplies_detail_to_send_node: "supplies_detail_to_send",
    store_eod_supplies_node: "store_eod_supplies",
    dispense_recovery_detail_node: "dispense_recovery_detail",
    outlet_register_status_node: "outlet_register_status",
    loading_item_issue_node: "loading_item_issue",
    expiry_barcodes_node: "expired_item_barcodes",
    test_mode_details_node: "test_mode_detail_to_send",
    test_mode_issues_node: "test_mode_issues",
    petty_cash_node: "petty_cash",
    petty_cash_to_HQ_node: "petty_cash_to_HQ",
    food_item_list_node: "food_item_list",
    non_food_item_list_node: "non_food_item_list",
    non_food_items_issue_collection: "non_food_items_issue",
    order_id_node: "order_id",
    order_item_id_node: "order_item_id",
    offline_dispenser_queue_node: "offline_dispense_queue",
    dispense_local_status_node: "dispense_local_status",
    issues_enum_node: "issues_enum",
    refund_data_list_node: "refund_data_list",
    replace_data_to_send_node: "replace_data_to_send",
    reconcile_data_node: "reconcile_data", //RAJESH 
    reconcile_check_data_node: "reconcile_data_check",
    reconcile_data_last_load_node: "reconcile_data_last_load", //RAJESH
    offline_po_request_node: "offline_po_request", //RAJESH TO STORING OFFLINE DATA FOR THE PO REQUESTS
    veg_nonveg_node: 'veg_nonveg', //for storing the details for veg items and non veg items
    menu_bands_node: 'menu_bands',
    batch_order_details_node: "batchOrderDetail",
    map_master_id_node: "map_master_id",
    outlet_register_status_node: "outlet_register_status",
    application_users_node:"app_users",
    users_access_details_node:"users_access_details",
    reconcile_summary_node:"reconcile_summary",
    sales_summary_node:"sales_summary"
};